# Generated by Django 5.1 on 2024-08-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0003_alter_bug_assigned_to_alter_bug_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
