# Generated by Django 5.1 on 2024-08-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0004_alter_bug_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='screenshot',
            field=models.ImageField(blank=True, default='project_bug.jpeg', upload_to='screenshots/'),
        ),
    ]
