# Generated by Django 5.1 on 2024-08-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0006_alter_bug_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='screenshot',
            field=models.ImageField(blank=True, default='screenshots/project_bug.jpeg', upload_to='screenshots/'),
        ),
    ]
