# Generated by Django 5.1 on 2024-08-09 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0003_alter_customuser_options_alter_customuser_managers_and_more'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='manager',
            field=models.ForeignKey(limit_choices_to={'user_type': 'MA'}, on_delete=django.db.models.deletion.CASCADE, to='customuser.customuser'),
        ),
    ]
